### PR TITLE
 Added -lrt flag back due to CentOS 6 compilation errors

### PR DESCRIPTION
**Pull request by lorenzocipriani**
Hi Jonathan.
I tried to build the DMRGateway on a CentOS 6 system and make was failing the process with these errors:
StopWatch.o: In function `CStopWatch::elapsed()':
/usr/local/src/DMRGateway/StopWatch.cpp:98: undefined reference to `clock_gettime'
StopWatch.o: In function `CStopWatch::start()':
/usr/local/src/DMRGateway/StopWatch.cpp:88: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make: *** [DMRGateway] Error 1

So I added the -lrt flag back to the Makefile

### CODE REVIEW

**Comment by g4klx** [comment]
I'm concerned that this will break things for other versions of Linux. CentOS 6 is getting old.

**Comment by lorenzocipriani** [comment]
I can add a distro+release check for activating or not that flag, if you
prefer.
Let me know.

**Comment by g4klx** [comment]
Yes, a selective use of that flag is to be preferred.

**Comment by lorenzocipriani** [comment]
Ok. I'll work on that this Sunday and I'll send you an updated PR

**Pull request closed without merging**
