### PR TITLE
XLX: Implement re-connect to startup reflector on period of RF inactivity.

### PR DESCRIPTION
**Pull request by hacknix**

### CODE REVIEW

**Comment by phl0** [comment]
Would that also re-connect to the XLX module or just make the connection to the XLX master?

**Comment by hacknix** [comment]
HI,

Sorry, maybe I should have been more clear. This change does the same as the BrandMeister and DMR plus relink options. 

i.e:

My default module is E (4005) 
I manually move the module to F (4006)
I have a QSO on F. 
When I have finished, my QSO, after 10 minutes of XLX not being activated by RF (traffic on TG6 on my system) the DMRGateway automatically re-links to my default module E (4005). 

Does that make sense?

73

Simon

**Comment by phl0** [comment]
Absolutely. I will test that :+1:

**Comment by oe1kbc** [comment]
Perfect Thank you
Kurt

**Comment by phl0** [comment]
Tested and gave an issue: If I set Relink to 0 it links and immediately re-links back. So made a PR to fix it: https://github.com/hacknix/DMRGateway/pull/1

**Comment by hacknix** [comment]
Well spotted! Thanks :-) 

On 20 June 2017 15:25:52 BST, "Florian (DF2ET)" <notifications@github.com> wrote:
>Tested and gave an issue: If I set Relink to 0 it links and immediately
>re-links back. So made a PR to fix it:
>https://github.com/hacknix/DMRGateway/pull/1
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/g4klx/DMRGateway/pull/23#issuecomment-309772816

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by phl0** [comment]
I made a pull request to your repo. I wonder if that will be included in your PR to Jonathan's repo automatically if you accept it :-) Let's see ... (I am not a git professional)

**Comment by hacknix** [comment]
Well, that seemed to work - your PR is now included in mine.

**Comment by phl0** [comment]
Hrhr, nice experiment. Tnx. Didn't know that this works. :-)

**Pull request merged**
