### PR TITLE
Alter XLX link/unlink log message

### PR DESCRIPTION
**Pull request by g0wfv**
Convert command number to reflector letter

### CODE REVIEW

**Comment by g4klx** [comment]
I think it would be better to use the same logic as used in the voice unit to convert the room/reflector number into a letter. It's more obvious and easy to understand. Something like:

char c = ('A' + (n % 100U)) - 1U;

and use that, c being the letter, and n the number.

**Comment by phl0** [comment]
+1
Thought the same while reading the PR

**Comment by g0wfv** [comment]
I never did understand the % operator (modulus is it?) but it's done and seems to work ......

**Comment by phl0** [comment]
Jepp it is the modulus operator.

**Comment by g4klx** [comment]
Can you lose the space between the reflector number and the module letter, so it's "XLX950E" not "XLX950 E" please.

**Comment by phl0** [comment]
The version with space would it make look like the D-Star conventions.

**Comment by g0wfv** [comment]
I had the space for parity with ircDDBGateway and MMDVMHost LCD layouts...... At least I thought they had a space?!

**Comment by phl0** [comment]
I think they have. Due to the 8char layout of D* callsigns.

**Comment by g0wfv** [comment]
Jon, your call, but I think it's better to maintain the "standard" as XLX was born from D-Star .....?!

**Comment by g0wfv** [comment]
I've not got ircDDBGateway running (or installed for that metter) right now so unable to confirm ......

**Comment by g4klx** [comment]
I didn't think there was a space. I'll merge it then.

**Comment by phl0** [comment]
There is:

bildschirmfoto vom 2017-10-04 21-00-30

**Pull request merged**
